# Generated by Django 4.2.10 on 2024-02-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_author_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_name',
            field=models.CharField(default=1, max_length=100, verbose_name='img-name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photo/%Y%m%d/'),
        ),
    ]
