# Generated by Django 4.2.10 on 2024-02-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_image_name_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='introduction',
            field=models.TextField(default=1, max_length=500, verbose_name='img_story'),
            preserve_default=False,
        ),
    ]
