# Generated by Django 4.2.10 on 2024-02-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photo_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='introduction',
            field=models.TextField(max_length=500, null=True, verbose_name='img_story'),
        ),
    ]
