# Generated by Django 4.2.10 on 2024-02-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_alter_photo_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_name',
        ),
    ]
